# Generated by Django 6.0.5 on 2026-05-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='med',
            name='unit',
            field=models.CharField(default='mg', max_length=20),
        ),
    ]
