# Generated by Codex on 2026-07-01

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_med_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med',
            name='time_taken',
            field=models.DateTimeField(default=tracker.models.default_time_taken),
        ),
    ]
